[build]
  command = "npm run build"
  publish = "build/client"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  function = "entry.server"
  path = "/*"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry.server"
  status = 200

[build.environment]
  NODE_VERSION = "18"